global.collect = 0
showtext = 0
xi = 500
yi = 600
collect_shake = 0;
previousrank = 0;
rank_scale = 1;
collect_shake = 0;
ded = false
hud_posY = 0;
global.rank = "d";
global.laps = 0;
   global.timesup = false
message = "TEST"
global.ptfont = font_add_sprite_ext(spr_font, "ABCDEFGHIJKLMNOPQRSTUVWXYZ!.1234567890:", true, 0);
global.numfont = font_add_sprite_ext(spr_numfont,"0123456789/", true,1)